### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by jsroyal** [cassidoo/todometer#1]
Hi!,
 Can you please add demo link how it works.
I clone your repo and try into chrome through index.html but nothing to show.

**Comment by jsroyal** [comment]
![image](https://cloud.githubusercontent.com/assets/10773353/25554485/356ab5c6-2cec-11e7-8024-114bd8c210cb.png)
Here it is.
I'm a newbie in java script.

**Comment by cassidoo** [comment]
Hi!  Will do.  I pushed it a little too early and have a lot more to push to show what it is. :)  Thanks for checking it out early!
