### ISSUE TITLE
feature: edit already added todo

### ISSUE THREAD

**Issue by tunnckoCore** [cassidoo/todometer#10]
Currently it isn't possible. (because typos by fast fingers ...)

**Comment by cassidoo** [comment]
Smart. I will say that if you wanted to just recreate that todo and delete the previous bad one, that would work, but I totally see your point. Will fix!!

**Comment by tunnckoCore** [comment]
Haha, yea totally, i'm just doing that currently. :)

**Comment by Shobhit1** [comment]
Hey @cassidoo, I have implemented this feature. Below is the gif of how it is working.
If you think this is good, I will raise the PR. Please let me know.
![todometer_edit](https://user-images.githubusercontent.com/4496335/28051669-6fd3a69c-65cb-11e7-9f1a-1dd28ca06018.gif)
