### ISSUE TITLE
Unable to open application on macOS High Sierra

### ISSUE THREAD

**Issue by tannerdolby** [cassidoo/todometer#102]
I downloaded the `.zip` file for mac from [here](https://github.com/cassidoo/todometer/releases), unfortunately after the download is complete and I try to open the application, I'm greeted with this message:

<img width="526" alt="Screen Shot 2021-05-30 at 11 04 02 AM" src="https://user-images.githubusercontent.com/48612525/120115035-c7d5bb80-c136-11eb-9880-00b1d42361a2.png">

I could "allow" the security preferences to open this app even though its not from a "identified developer" but Mac docs don't recommend doing this. Let me know if this is normal behavior and/or if its probably fine just to allow the application to be opened against the security recommendation. Thank you! @cassidoo

**Comment by cassidoo** [comment]
Hey Tanner! Yes, that's expected. You can do "open anyway" in your security settings. Maybe someday I'll fork over the cash to Apple to make this an "identified" app :)

**Comment by tannerdolby** [comment]
Hi Cassidy! Okay, great. Thanks for the heads up :)
