### ISSUE TITLE
Linux package seems not working correctly

### ISSUE THREAD

**Issue by tunnckoCore** [cassidoo/todometer#11]
I just cloned the repo, install deps and then ran `npm run package-linux`, but when i started it (the `./release-builds/todometer-linux-x64/todometer`), it is just empty screen with background, no form, no list, no date.

![2017-05-01-16 26 52_1280x1024_scrot](https://cloud.githubusercontent.com/assets/5038030/25580626/1b4d2930-2e8b-11e7-88be-1e828a8f2175.png)

**Comment by cassidoo** [comment]
Thank you for letting me know! I'll get my hands on a Linux machine and figure out what could be going wrong here.

**Comment by cassidoo** [comment]
Can you try running `npm run build:less` and then `npm run package-linux`?  I have a feeling that might be part of it.

**Comment by tunnckoCore** [comment]
Yea, initially, but then realized that and look over the scripts, then ran it then rebuild it again. Same.

**Comment by tunnckoCore** [comment]
@cassidoo cool :) I may try it soon! :tada:
