### ISSUE TITLE
SIGTERM seems to not work? hm

### ISSUE THREAD

**Issue by tunnckoCore** [cassidoo/todometer#12]
Not sure. I'm new to electron too. But basically, i'm on ArchLinux and I have shortcut to `kill` command, it works for absolutely everything, even for other Electron Apps - here this not work. When using `htop`, and then F9 which lists what signal to send, the default always is SIGTERM. When I send SIGKILL it close the todometer apps, correctly. I just intentionally "executing it in terminal", so i'm seeing that when SIGTERM is send nothing happen, app stays.

**Comment by cassidoo** [comment]
Hm, I can't test this on Linux at this point so I'll definitely get back to you. I think this has to do with how I wanted it to be able to reopen on close really easily, that might have disabled something on the Linux end.

**Comment by cassidoo** [comment]
@tunnckoCore would you mind trying it again?

**Comment by tunnckoCore** [comment]
Still seems not working. I seen that you added Ctrl + Q shortcut that works properly and exits both Todometer and Electron (i'm using `npm start`), but when I use my shortcut to `kill` command which is Cmd + Q, it only closes the Todometer window, but does not exits the Electron.
