### ISSUE TITLE
Minimize to Tray support.

### ISSUE THREAD

**Issue by ftk789** [cassidoo/todometer#120]
The ability to minimize to Tray and keep the app up and running, Thanks for an amazing project btw.

**Comment by cassidoo** [comment]
@ftk789 thank you!

Which OS are you on? This functionality exists but maybe I'm not understanding.

**Comment by ftk789** [comment]
> 

On Windows 10, It's non existent, Minimizing the program just puts it in the taskbar, Exiting the program exits it fully. Big fun BTW, Your work is AMAZING.

**Comment by cassidoo** [comment]
Ah ah I misunderstood the difference between the tray and the taskbar! Definitely looking into that. There was some weirdness with Electron when I tried it before, but maybe with the latest updates it's better!

And thank you for your kind words <3

**Comment by ftk789** [comment]
Can't wait, It's amazing right now, But would be Awesome with a tray of course, Thanks for an amazing project.
