### ISSUE TITLE
Can add empty todo

### ISSUE THREAD

**Issue by flowryaan** [cassidoo/todometer#13]
I guess it would be better if you can not add empty todos?

![screen shot 2017-05-01 at 15 14 56](https://cloud.githubusercontent.com/assets/8149519/25581657/00f56494-2e81-11e7-9dcc-1b3ce742826b.png)

**Comment by cassidoo** [comment]
Ah, yeah, good call. I admit I originally did that just for myself so I could add an empty todo as a separator between todos, but it probably isn't the best idea. ;)

**Comment by cassidoo** [comment]
Fixed by #29
