### ISSUE TITLE
Error message on opening

### ISSUE THREAD

**Issue by procaviacapensis** [cassidoo/todometer#17]
JavaScript error "Uncaught Exception ... TypeError - can't read property 'show' of null..."

Appears not to prevent normal functioning of app.
<img width="427" alt="todometer" src="https://cloud.githubusercontent.com/assets/28265192/25585175/4390e598-2e91-11e7-9dfe-bf7c596a43f6.png">

**Comment by cassidoo** [comment]
Would you mind letting me know what kind of machine you're on? Another person brought this up (#3) and I'm trying to narrow it down.

**Comment by l3s777** [comment]
Hey! I am running it on MAC OS (Sierra) same message.
![screen shot 2017-05-10 at 5 23 40 pm](https://cloud.githubusercontent.com/assets/7820754/26516243/50a9500c-4283-11e7-95de-554ea0186bd5.png)
