### ISSUE TITLE
No support for keyboard shortcuts

### ISSUE THREAD

**Issue by davidleger95** [cassidoo/todometer#18]
Keyboard shortcuts such as CMD+Q (quit), CMD+H (hide), etc. do not work. 

Not sure if this should be considered a feature request or a bug, haha. 🙃  

Good job with the app though! It's a fun side project.

**Comment by cassidoo** [comment]
Thanks! I noticed that too, will def fix. :)

**Comment by benlikescode** [comment]
Hey! I added a pull request with CMD+Q

**Comment by cassidoo** [comment]
Cmd+Q works now, others will follow. :)

**Comment by cassidoo** [comment]
Keyboard shortcuts enabled.
