### ISSUE TITLE
Feature Request - Nestable Todos

### ISSUE THREAD

**Issue by gerbilsinspace** [cassidoo/todometer#21]
First of all, thank you so much for your hard work so far. Todometer in it's current form is fantastic. 

I would like to have the ability to add sub-todos, for larger pieces of work which require breaking down into smaller chunks. Nestable todos would be ideal, or maybe a notes section, to explain the work in more detail. 

I'm happy to get working on a merge request after work on this one, as this would make todometer my go to app for todos.

**Comment by farskid** [comment]
It could be a good idea to be able to add checklist to todo items.

**Comment by cassidoo** [comment]
At the same time... you could also just add the subtasks as regular tasks ¯\_(ツ)_/¯

Simplicity!

**Comment by farskid** [comment]
@cassidoo Clever! as much as namespace is concerned, one could start todo titles with a hint.

* __chores:__ do a thing
* __chores:__ do another thing
* __chores:__ do anything else
