### ISSUE TITLE
Wrap long task text

### ISSUE THREAD

**Issue by antislice** [cassidoo/todometer#34]
Similar to what #30 is trying to resolve - sometimes I'll write a longer task out and it'll truncate after I hit enter. I think what I'd like is wrapping the longer text (what I'll pick if/when I can get around to it). But doing a "click to expand" or "hover to expand" could be good choices. 

edited to add - I really like this! just doing the "could be perfect for me if..." dev thing.

**Comment by farskid** [comment]
Sent a PR to solve the issue and add the feature. https://github.com/cassidoo/todometer/pull/36
