### ISSUE TITLE
Not refreshing on a new day

### ISSUE THREAD

**Issue by antislice** [cassidoo/todometer#38]
I double checked the dev.to post to make sure I wasn't imagining that it's supposed to do this. But I've had to manually refresh it every morning. I used the dmg installer on osx sierra (10.12.4), happy to add log files if someone points me to them.

**Comment by cassidoo** [comment]
Duplicate of #15. Noticed it only does it if the computer is awake overnight. Working on it! 👍

**Comment by antislice** [comment]
@cassidoo cool, sorry for making the duplicate! I thought #15 meant something else.
