### ISSUE TITLE
Editorconfig

### ISSUE THREAD

**Issue by rohanrk** [cassidoo/todometer#40]
A previous issue mentioned adding an .editorconfig file which still hasn't been added yet. Adding a .editorconfig and updating the documentation would be useful.

[editorconfig.org](http://editorconfig.org/)

**Comment by farskid** [comment]
Is it really necessary considering the fact that __ESLint__ is setup on the project?

**Comment by rohanrk** [comment]
Is it? I don't know how to tell. It's not listed as a dependency nor is it anywhere in .node_modules/
