### ISSUE TITLE
Repetitive Reminder

### ISSUE THREAD

**Issue by Godje** [cassidoo/todometer#42]
If Electron allows that, you may add the option to make a reminder for the item.
**What I mean by reminder, is** that, for example, you can add a "ASAP" check mark by the todo item. And then it will send a Windows notification _(like the one in Windows 10 on the right bottom. Something like a Chrome notification, I think you get what I am talking about)_ every other 2 minutes or so _(would be good to have a way to set it by yourself)_, so that you don't forget you have stuff to do.

**Comment by cassidoo** [comment]
Adding reminder notifications in version 2 coming soon™
Thanks for this!
