### ISSUE TITLE
Issue/Suggestion

### ISSUE THREAD

**Issue by Godje** [cassidoo/todometer#43]
I started using this app more actively later on and noticed one annoying thing - you can't unpause todos.
It has to be unpaused because the slogan says that make it and forget it, but I can't make it because it is in "Do Later" section =)

**Comment by cassidoo** [comment]
Hm, so that was intentional. I figure if I'm going to get the paused to-do item done, then I'll just hit done, and if not, I'll delete it. I'll think on that though. :)

**Comment by Godje** [comment]
Well you focus on the one you have to do that is not in the "Do Later" tab. And when you have done everything, you have to focus on the other tab. It goes a bit against the mental expectation =D
