### ISSUE TITLE
Application doesn't minimize to taskbar on windows

### ISSUE THREAD

**Issue by jaslloyd** [cassidoo/todometer#48]
Hey @cassidoo , 

I see in the code when the window 'close' button is clicked it's suppose to keep the application running in the background. On OS X this seems to be the normal behaviour when you hit 'close' window button it is still running however on Windows when you hit close it completely closes the application. This is also causing problems when doing development if you accidentally close the window there is no way to restore it and you need to kill the 'npm start' command and rerun it.

Do you want it to act the same on windows e.g. when the user hits the window close button, it minimizes to the taskbar instead of full closing? 

I already have this mostly working on windows, I want to also test on OS X before submitting a PR. Let me know if you would like this?

Jason

**Comment by cassidoo** [comment]
Hi Jason!
I'd love to see a PR for this. I can test it on a Mac if needed!

**Comment by TheDeployGuy** [comment]
Hey, was looking at the current PR's, it seems like #32 has a bunch of the changes required to make it work on both windows and mac. I haven't been able to test them and there seems to be some merge issues with that PR.

**Comment by oultrox** [comment]
@TheDeployGuy  @cassidoo  Any update on this? it looks like a great improvement for those who have a lot of windows opened like me haha, I thought about implementing it myself but the truth is that I know very little about Js and Electron.

**Comment by TheDeployGuy** [comment]
@oultrox I think once I know @cassidoo plans for PR #32 we can move forward. That PR addresses some of the same issues but still hasn't been accepted due to merge issues. If the original owner can't commit to fixing it I could take what they have done and try to get it in but want to be sure.

**Comment by cassidoo** [comment]
Updated this for version 2 coming soon™ (yes, years later, but better late than never?)

Making it so that on Windows, the X means "quit" instead of close. Experimented with the tray option that was in #32 and unfortunately just couldn't make everything work as smoothly as I would expect, so this is the solution we'll go with.

**Comment by dynamiccontent** [comment]
@cassidoo Any update on this? I am on windows and I can't get it to minimize to taskbar (tray)... Any kind of workaround to make this work?

**Comment by cassidoo** [comment]
@dynamiccontent do you have the latest version? I'm on Windows now and don't see the problems you're having.

**Comment by dynamiccontent** [comment]
@cassidoo I am using the https://github.com/cassidoo/todometer/releases/tag/v2.0.1 should be the latest right?
Let me paste a picture here (windows terms for taskbar, tray are confusing).
I would like it to minimize to this ![tray](https://i.imgur.com/68kc8YX.png).
I can minimize it fine to ![tray](https://i.imgur.com/isP6bqV.png).
Is this implemented or I am missing something? Thanks!
