### ISSUE TITLE
formatting of website off for particular page widths

### ISSUE THREAD

**Issue by dhood** [cassidoo/todometer#5]
Great project!
I happened to have my browser not at full width and noticed the installation badges don't quite align nicely.

1200px width on chrome on mac:
<img width="1220" alt="screen shot 2017-04-30 at 8 25 50 pm" src="https://cloud.githubusercontent.com/assets/5618076/25571332/8f7b1b8a-2de3-11e7-994a-ad27a5ecdf40.png">

**Comment by cassidoo** [comment]
Ooh thank you for letting me know!

**Comment by mysticuno** [comment]
I think #6 is working on fixing this
