### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by Godje** [cassidoo/todometer#52]
Since this is Electron app, there must be a build for Linux?
I am using Linux, and there isn't a big choice for a To-Do app this type. 
The meter thing is such a cool gimmick that it is a must for me. If it will be possible to make a release with a tarball or .deb...

**Comment by cassidoo** [comment]
Yes! I have no way of testing it on Linux though, so I haven't added a downloadable file. I am currently in the middle of wedding planning (it's a month away!) and will be maintaining the app + updating it more after that.

**Comment by Porgi** [comment]
@cassidoo You have us. I think everyone would like to provide feedback for possibility to use your app on Linux.
