### ISSUE TITLE
Reduce large repo size

### ISSUE THREAD

**Issue by farskid** [cassidoo/todometer#54]
I just cloned the repo and found out that it has a size around 150MB!
That's a huge size for a GitHub repo. So I figured out that something is wrong. By running some commands found out that the main large size is created by git holding a link to some files in the history that are removed from the current repo.
Most of those files had extensions such as `.dmg`, `.exe` or `.nupkg`. Removing the link to them in the history would do no harm and will result in small repo size.

I safely cleaned them on my local fork and the size is reduced from 150MB to about 130KB.

I'd be happy to send a PR and discuss the changes in details.

**Comment by cassidoo** [comment]
Hi there @farskid! Thanks for pointing this out! Apologies for the late reply, I got married this past week and have been slow to catch up to everything. I'd love it if you could send a PR for this! Thank you!

**Comment by MattiJarvinen-BA** [comment]
It's a hard thing to pull off since change @farskid proposes would a be rewrite of history and that would change every commit downstream from commit of those files invalidating all pull requests & repos.

There even seems to be a simple tool for something like this https://help.github.com/articles/removing-sensitive-data-from-a-repository/

> Tell your collaborators to rebase, not merge, any branches they created off of your old (tainted) repository history. One merge commit could reintroduce some or all of the tainted history that you just went to the trouble of purging.

**Comment by farskid** [comment]
@MattiJarvinen-BA Thanks for the notice. Rebase vs Merge has been a real issue since the beginning of the time and I'm on your side. But the thing is, The change I proposed would do no harm to commits, just telling git to remove the reference to those large files indexed in the history. After those changes, only the reference to those files would be removed and no other change to other commits.
