### ISSUE TITLE
App Image[Linux support]

### ISSUE THREAD

**Issue by bsucker98** [cassidoo/todometer#63]
Pls add an app image as it would support Linux ;)

**Comment by cassidoo** [comment]
I'm not familiar with Linux app images! Do you know how to add that in Electron?

**Comment by bsucker98** [comment]
Ah! I wish I know :/...just maybe, these would help https://howtoelectron.app/a-complete-guide-to-packaging-your-electron-app/ https://www.christianengvall.se/electron-packager-tutorial/
:)
In no way trying to be inconvenience or asking u to go through those articles & fulfill my request..
I jst love ur app:) simple, got all the features I want & not bloated..It's jst cool

**Comment by bsucker98** [comment]
OR u could go with snap another universal package manager for Linux
https://docs.snapcraft.io/build-snaps/electron

**Comment by probonopd** [comment]
Presumably an [AppImage](https://appimage.org/) is meant. electron-builder can make them easily.
