### ISSUE TITLE
Hide on mac!

### ISSUE THREAD

**Issue by kbohinski** [cassidoo/todometer#7]

**Comment by cassidoo** [comment]
What does this mean?

**Comment by kbohinski** [comment]
Im not sure if it is actually called hide, but its command+h. Other electron apps have it so it may be built into electron...

**Comment by cassidoo** [comment]
So it's the same functionality as hitting the Mac red X button?

**Comment by kbohinski** [comment]
I believe it hides all windows for that application. So I guess the same functionality in this case since it is only one window.

Here is another electron app that has it. https://github.com/sqlectron/sqlectron-gui/blob/38603d22e0d940efbb9c18ba54f6adf66056dccd/src/browser/menu/darwin.js

**Comment by cassidoo** [comment]
Fixed!
