### ISSUE TITLE
Ability to resume a "do Later" task

### ISSUE THREAD

**Issue by warpdesign** [cassidoo/todometer#76]
Using the `pause` button it's possible to postpone a task. However I don't see a way to resume a task (without cancelling or finishing it): is it possible?

**Comment by cassidoo** [comment]
It’s not, if you want to do the task you just complete it!
If you want to move everything from “Paused” to the “Pending” list again, you can reset everything with the “Reset all” button at the bottom.

**Comment by warpdesign** [comment]
I want to work on it, it doesn't mean I want to complete it. Reseting everything is not an option.

**Comment by cassidoo** [comment]
I see what you mean. I kind of see both the “pending” and “do later” lists as one but I could see wanting to move them between each other. I’ll look into implementing this!

**Comment by cassidoo** [comment]
Update: just finished implementing this but I’m on a plane and can’t push it. Will do and cut a release soon.
