### ISSUE TITLE
Notifications being displayed despite being disabled

### ISSUE THREAD

**Issue by markvincze** [cassidoo/todometer#77]
I've set the reminder notifications to "Never":

![image](https://user-images.githubusercontent.com/1122274/75249872-64dcd280-57d7-11ea-8ebc-acbfce327527.png)

Yet I'm getting regular reminder notifications (I didn't took note of the exact times, but felt like once per hour). The notifications look like this.

![image](https://user-images.githubusercontent.com/1122274/75253849-a5404e80-57df-11ea-9864-50addd4d3517.png)

This is happening on Windows 10.

**Comment by cassidoo** [comment]
Sorry about the excess notifications! Could’ve sworn I fixed all of those bugs. I’ll get on this ASAP.

**Comment by cassidoo** [comment]
Heads up, just fixed this! I’m on a plane and can’t push right now, but will cut a release in the next day or two. Thank you for the heads up!

**Comment by markvincze** [comment]
Wow, that was quick, thanks a bunch! :)
