### ISSUE TITLE
Undo/Redo functionality for the cards themselves

### ISSUE THREAD

**Issue by BenjaFriend** [cassidoo/todometer#78]
Currently the undo/redo functionality is only for typing in the text box. I would _love_ if I could undo the creation of cards and the changing of their status.

**Comment by cassidoo** [comment]
I do like the idea of undoing the status changes, I’ll put something for that together.
For undoing the creation of cards, for now I’ll suggest using the X button to delete them! Maybe I could throw in a keyboard command or something for a quick removal.
