### ISSUE TITLE
[Feature Request] Add an option for an Example Notification 

### ISSUE THREAD

**Issue by BenjaFriend** [cassidoo/todometer#79]
My first time using this app I found myself wondering "Well there's notifications, but what are they like? How intrusive is it? Is there a noise?" and I had no way to test it. 

I think it could be a useful to have a "Test Notification" similar to Slack's "Show me an example notification" feature.

Thanks!

**Comment by cassidoo** [comment]
Just implemented this! I’m on a plane so I’ll push when I’ve landed. Good idea, thanks for the request!
