### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by ewingd** [cassidoo/todometer#9]
Can we get a build for Linux?

**Comment by tunnckoCore** [comment]
Git clone and `npm start`, before that install `electron` globally.

I also built `npm run package-linux`, but when start it is empty, dont know why.

**Comment by cassidoo** [comment]
Working on an installer for that! I personally don't have a Linux machine to test on, but once I do I'll make an official build. <3

Thanks!

**Comment by tunnckoCore** [comment]
Haha, great. I'm full linux user, everyday from ~4 years, so... :)

**Comment by aditiapratama** [comment]
Great to know Linux support is coming, thanks
