### ISSUE TITLE
yarn.lock is not available

### ISSUE THREAD

**Issue by calebdeji** [cassidoo/todometer#92]
I just checked the .gitignore file, yarn.lock is prohibited. Is there a reason for that?

**Comment by hadenpf** [comment]
Considering 3687b07's `Hide yarn.lock for now` comment and this line:

https://github.com/cassidoo/todometer/blob/74619bd75f0c3f80aa6dad2d44a9f60927ef9293/.gitignore#L6-L7

It looks like she has a reason for it - it'd be nice to get an idea of why, at least.

**Comment by cassidoo** [comment]
No longer a thing!
