### ISSUE TITLE
opening port 3000 does not seem to be working once webserver via yarn electron-dev is up.

### ISSUE THREAD

**Issue by nisarhassan12** [cassidoo/todometer#97]
Opening browser preview for port `3000` does not work. This is what I get in the console.

![image](https://user-images.githubusercontent.com/46004116/96475684-bdbd1780-124d-11eb-9999-23d82690e0e1.png)

And in the window there is a blank screen with nothing inside of it.

There is no error in the terminal where the task `yarn electron-dev` is running.

![image](https://user-images.githubusercontent.com/46004116/96490531-62dded00-125a-11eb-9f23-5fc916a8bb96.png)

**Comment by hoangddt** [comment]
I am encountered this problems too. This can not run on the browser. So I used: `yarn run electron-dev` and make the modification on the code which reflect on the electron app.
I think the script is intend to use with electron.

**Comment by cassidoo** [comment]
@hoangddt is correct! This is working as expected, it is meant to be an Electron application.
